baseURL: http://example.org/
languageCode: en-us
title: Timer | Responsive Multipurpose Bootstrap Hugo Template
theme: timer-hugo
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: about
      weight: 2
    - name: Service
      url: service
      weight: 3
    - name: Gallery
      url: gallery
      weight: 4
    - name: Blog
      url: blog
      weight: 5
    - name: Contact
      url: contact
      weight: 6
params:
  about:
    content: We build support for scientists, researchers and public audiences to use the Atlas of Living Australia
    enable: yes
    image: images/about/about.jpg
    title: ABOUT US
  author: Science and Decision Support team
  banner:
    bgImage: images/slider.jpg
    btn: yes
    btnText: Go to ALA website
    btnURL: https://www.ala.org.au/
    description: ATLAS OF LIVING AUSTRALIA
    enable: yes
    flipText:
      - title: TRANSPARENCY
      - title: RESEARCH SUPPORT
      - title: DATA VISUALISATION
    heading: THE SCIENCE AND DECISION SUPPORT TEAM
  contactFormAction: '#'
  cta:
    btnText: Contact with me
    btnURL: /contact
    content: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus
      commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium.
    enable: yes
    title: Get in touch
  dateFormat: 6 January 2006
  description: Airspace Hugo theme
  googleAnalitycsID: Your ID
  home: Home
  logo: images/logo.png
  portfolio:
    enable: yes
    subtitle: Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor
      neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat,
      nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus.
    title: Latest Works
  socialIcon:
    - icon: ion-social-github
      url: '#'
    - icon: ion-social-twitter
      url: '#'
    - icon: ion-social-linkedin
      url: '#'
