baseURL: http://example.org/
languageCode: en-us
title: Timer | Responsive Multipurpose Bootstrap Hugo Template
theme: timer-hugo
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: about
      weight: 2
    - name: Projects
      url: portfolio
      weight: 3
    - name: Blog
      url: blog
      weight: 4
    - name: Contact
      url: contact
      weight: 5
markup:
  highlight:
    style: tango
params:
  about:
    content: We support the Atlas of Living Australia to make our data more robust and accessible for scientists, researchers and public audiences
    enable: yes
    image: images/about/teamphoto.jpg
    title: ABOUT US
  author: Science and Decision Support team
  banner:
    bgImage: images/galah_image.jfif
    btn: yes
    btnText: Go to ALA website
    btnURL: https://www.ala.org.au/
    description: ATLAS OF LIVING AUSTRALIA
    enable: yes
    flipText:
      - title: SCIENTIFIC TRANSPARENCY
      - title: RESEARCH SUPPORT
      - title: DATA VISUALISATION
    heading: THE SCIENCE AND DECISION SUPPORT TEAM
  contactFormAction: '#'
  cta:
    btnText: Contact us
    btnURL: /contact
    content: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus
      commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium.
    enable: yes
    title: Get in touch
  dateFormat: 6 January 2006
  description: Airspace Hugo theme
  googleAnalitycsID: Your ID
  home: Home
  logo: images/ALA_Logo_Inline_RGB_cropped.png
  portfolio:
    enable: yes
    title: Latest Projects
  socialIcon:
    - icon: ion-social-github
      url: 'https://github.com/AtlasOfLivingAustralia/science'
    - icon: ion-social-twitter
      url: 'https://twitter.com/atlaslivingaust'
  customCss: ["css/custom.css"]

